import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'duo-green': '#58CC02',
        'duo-green-dark': '#58A700',
        'duo-mask-green': '#89E219',
        'duo-macaw': '#1CB0F6',
        'duo-macaw-dark': '#1899D6',
        'duo-cardinal': '#FF4B4B',
        'duo-cardinal-dark': '#EA2B2B',
        'duo-bee': '#FFC800',
        'duo-bee-dark': '#E5A800',
        'duo-fox': '#FF9600',
        'duo-fox-dark': '#D97800',
        'duo-lily': '#CE82FF',
        'duo-whale': '#2B70C9',
        'duo-eel': '#4B4B4B',
        'duo-wolf': '#777777',
        'duo-hare': '#AFAFAF',
        'duo-swan': '#E5E5E5',
        'duo-polar': '#F7F7F7',
        'duo-snow': '#FFFFFF',
        
        'sky-start': 'var(--color-sky-start)',
        'sky-end': 'var(--color-sky-end)',
        'grass-start': 'var(--color-grass-start)',
        'grass-end': 'var(--color-grass-end)',
        'grass-accent-1': 'var(--color-grass-accent-1)',
        'grass-accent-2': 'var(--color-grass-accent-2)',
        'grass-accent-3': 'var(--color-grass-accent-3)',
        'sun-start': 'var(--color-sun-start)',
        'sun-end': 'var(--color-sun-end)',
        'earth-1': 'var(--color-earth-1)',
        'earth-2': 'var(--color-earth-2)',
        'earth-3': 'var(--color-earth-3)',
        'success-bg': 'var(--color-success-bg)',
        'success-text': 'var(--color-success-text)',
        'success-btn': 'var(--color-success-btn)',
        'success-btn-shadow': 'var(--color-success-btn-shadow)',
        'error-bg': 'var(--color-error-bg)',
        'error-text': 'var(--color-error-text)',
        'error-btn': 'var(--color-error-btn)',
        'error-btn-shadow': 'var(--color-error-btn-shadow)',
        'primary-blue': 'var(--color-primary-blue)',
        'primary-blue-shadow': 'var(--color-primary-blue-shadow)',
        'progress-green': 'var(--color-progress-green)',
        'progress-bg': 'var(--color-progress-bg)',
        'heart-pink': 'var(--color-heart-pink)',
        'text-grey': 'var(--color-text-grey)',
        'option-selected-bg': 'var(--color-option-selected-bg)',
        'option-selected-border': 'var(--color-option-selected-border)',
        'level-complete-title': 'var(--color-level-complete-title)',
      },
      fontFamily: {
        sans: ['var(--font-nunito)', 'var(--font-varela)', 'sans-serif'],
      },
      boxShadow: {
        'btn-green': '0 4px 0 #58A700',
        'btn-blue': '0 4px 0 #1899D6',
        'btn-red': '0 4px 0 #EA2B2B',
        'btn-orange': '0 4px 0 #D97800',
        'btn-disabled': '0 4px 0 #AFAFAF',
        'card': '0 2px 0 #E5E5E5',
      },
      animation: {
        'celebrate': 'celebrate 0.3s ease-out',
        'float-up': 'float-up 0.8s ease-out forwards',
        'flame': 'flame 0.5s ease-in-out infinite',
        'shake': 'shake 0.3s ease-in-out',
        'bounce-in': 'bounce-in 0.5s cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        celebrate: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.1)' },
          '100%': { transform: 'scale(1)' },
        },
        'float-up': {
          '0%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(-30px)' },
        },
        flame: {
          '0%, 100%': { transform: 'scale(1) rotate(-2deg)' },
          '50%': { transform: 'scale(1.1) rotate(2deg)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-5px)' },
          '75%': { transform: 'translateX(5px)' },
        },
        'bounce-in': {
          '0%': { transform: 'scale(0.8)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};
export default config;
